### ISSUE TITLE
snapshot_health check has uninitialized values

### ISSUE THREAD

**Issue by furlongm** [willemdh/check_netapp_ontap#1]
root@mon:~# perl /usr/local/lib/nagios/plugins/check_netapp_ontap -H netapphost -u adminuser -p adminpassword -o snapshot_health
Use of uninitialized value in string eq at /usr/local/lib/nagios/plugins/check_netapp_ontap line 1020.
Use of uninitialized value in string eq at /usr/local/lib/nagios/plugins/check_netapp_ontap line 1020.
Use of uninitialized value in string eq at /usr/local/lib/nagios/plugins/check_netapp_ontap line 1020.
Use of uninitialized value in string eq at /usr/local/lib/nagios/plugins/check_netapp_ontap line 1020.
OK - No problems found (58 checked)

**Comment by willemdh** [comment]
Are you still having this issue Furlongm?

**Comment by furlongm** [comment]
@waipeng can you check if this still occurs when run from the command line as above?

**Comment by sandipok** [comment]
Yeah the same line I am also facing the issue. 

snapshot_health
Use of uninitialized value in string eq at /usr/lib64/nagios/plugins/check_netapp_ontap.pl line 1020.
Use of uninitialized value in string eq at /usr/lib64/nagios/plugins/check_netapp_ontap.pl line 1020.
OK - No problems found (7 checked)

is anybody looking into this ?

**Comment by sandipok** [comment]
I am not sure what this "next" do here, but I used work arround for it as below 

			our $TXT=$nahVol->child_get("volume-state-attributes")->child_get_string("is-moving");     # added by me
			if ( defined $TXT){ # added by me
			if ( "$TXT" eq "true") {
                                 next;
                         }
			}   # added by me

Diff shows the modification : 

 diff  check_netapp_ontap.pl  check_netapp_ontap.pl.orig
1020,1022c1020
<                       our $TXT=$nahVol->child_get("volume-state-attributes")->child_get_string("is-moving");
<                       if ( defined $TXT){
<                       if ( "$TXT" eq "true") {
---
>                       if ($nahVol->child_get("volume-state-attributes")->child_get_string("is-moving") eq "true") {
1025d1022
<                       }

**Comment by waipeng** [comment]
Hi @willemdh, I've created a pull request that fixes this. Thanks!

**Comment by willemdh** [comment]
Thank you Waipeng for your contribution. I've merged your undefined check.

**Comment by willemdh** [comment]
I'm guessing this issue can be closed? Let me know if not.
