### ISSUE TITLE
no output for volume_health

### ISSUE THREAD

**Issue by catchvenki** [willemdh/check_netapp_ontap#11]
hi team,
First of all thanks for this wonderful script.
i have a 2 netapp storages. one with 170 volumes and another with 500 volumes. For the 170 volumes everything works fine. but for 500 volumes, when i have given command to display volume_health with more than 95% it is running for than more than 1 hour with no output or error. may i know whether script has any issue with the number of volumes.?
Please help me on this.

**Comment by willemdh** [comment]
I haven't seen or heard any issue with lots of volumes. But then again I only have +- 200 I think. Maybe other users can let us know their experiences. 
Maybe you should try debug the script with Eclipse and EPIC and see where things go wrong. It might be related to some weird name or state.

**Comment by catchvenki** [comment]
hi 

thanks for your reply

i am using the below command

check_netapp_ontap.pl -H 10.0.0.5 -u test_user -p test_password -o volume_health --critical 95%

this is running for than 2 hours with no output.

i am using check_netapp_ontap-2.5.10

**Comment by willemdh** [comment]
Yes you could check the dev branch, but it hasn't been properly tested yet and has some issues. (I'm not using it myself for production) Use at own risk..
v2.06.151101

**Comment by catchvenki** [comment]
As the issue is facing only on volume_health, any permission on the storage side can be the issue?

**Comment by catchvenki** [comment]
hi willemdh,

could you please tell me the syntax for showing only first ten volumes in netapp storage in your script.

present scipt 
check_netapp_ontap.pl -H 10.0.0.5 -u test_user -p test_password -o volume_health --critical 95%

just to know whether less number is displaying ouput fast.

**Comment by willemdh** [comment]
@catchvenki Just something I found:
There is no such thing as hte first 10 or so, but you could use the -m exclude or -m include for volume_health

**Comment by catchvenki** [comment]
hi team,
please help me on this 

anything related to volume_health it is not listing

i tried to list offline volumes thats also not working

**Comment by willemdh** [comment]
@catchvenki Closing this, let us know if you are still experiencing issues with the latest release
