### ISSUE TITLE
Getting error when invoking the check_netapp_ontap.pl

### ISSUE THREAD

**Issue by mskrishna20051974** [willemdh/check_netapp_ontap#2]
Hi,

I am getting this error while invoking the perl command
[root@blr-monitor libexec]# /usr/bin/perl ./check_netapp_ontap.pl -H 10.0.0.20 -u root -p password disk_health

Failed test query: in Zapi::invoke, cannot connect to socket

Please help me out.

Thanks,
Krishna M S

**Comment by willemdh** [comment]
Are there any other checks who do work?

**Comment by mskrishna20051974** [comment]
Hi,

This is not a cluster. 

It is an NetApp FAS 2040

Thanks,
Krishna M S

**Comment by willemdh** [comment]
Krishna, 

This plugin i only for NetApp ontap cluster mode.

Grtz
