### ISSUE TITLE
disk_health netapp FAS8080 cdot 8.3.2 - state is unknown

### ISSUE THREAD

**Issue by joke24** [willemdh/check_netapp_ontap#24]
Hi,
we got a new netapp fas8080 with cdot os version 8.3.2.
When I'm trying to get the disk_health status, the plugin fails with the output:

> 4.1.8 state is unknown, 2.11.6 state is unknown, 3.10.12 state is unknown, 1.0.0 state is unknown (...)

Is there a chance to get this fixed?
How can I assist you doing that?

Thanks a lot!

**Comment by willemdh** [comment]
Is that an Ontap Cluster? The plugin only works with Ontap Clusters.

**Comment by joke24** [comment]
yes it's an ontap cluster.

**Comment by willemdh** [comment]
Well as I'm still on 8.2 where the plugin works fine, I fear I can't help you. You should try debugging it and see where things go wrong.

**Comment by joke24** [comment]
can you help start debugging? I'm sorry, but I don't know how to use the netapp api.

**Comment by willemdh** [comment]
Read through this:

https://outsideit.net/debug-perl-epic-eclipse/

**Comment by Napsty** [comment]
I just tested the disk_health command on a NetApp FAS8040 with NetApp Release 8.3.2P1 and it works.

    ./check_netapp_ontap.pl -H mynetapp -u monitoring -p secret -o disk_health
    OK - No problems found (288 checked)

**Comment by Napsty** [comment]
... and also detects a failed drive correctly:

    ./check_netapp_ontap.pl -H mynetapp -u monitoring -p secret -o disk_health
    1.11.11 state is failed

@joke24  Maybe these disks really have an unknown status? You should verify this in the UI, too.

**Comment by willemdh** [comment]
@joke24 Were you ever able to resolve this?

**Comment by willemdh** [comment]
@joke24 Closing this, let us know if you are still experiencing issues.
