### ISSUE TITLE
volume_health has uninitialized value 

### ISSUE THREAD

**Issue by ditol** [willemdh/check_netapp_ontap#3]
High, when volumes are in offline state, we get an uninitialized value:
 /usr/lib64/nagios/plugins/check_netapp_ontap.pl -H onvarjv-ups -u ONVARJV\nagiosmon -p xxxxxxxx -o volume_health --warning 93% --critical 96% -m exclude,worm
Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/check_netapp_ontap.pl line 1197.
Use of uninitialized value in division (/) at /usr/lib64/nagios/plugins/check_netapp_ontap.pl line 1197.
Illegal division by zero at /usr/lib64/nagios/plugins/check_netapp_ontap.pl line 1197.

I added a check on volume state in 'space_threshold_helper':
sub space_threshold_helper {
        # Test the various monitored object values against the thresholds provided by the user.
        my ($intState, $strOutput, $hrefVolInfo, $hrefThresholds, $intAlertLevel) = @_;

```
    foreach my $strVol (keys %$hrefVolInfo) {
            my $bMarkedForRemoval = 0;

            # Test added by Didier Tollenaers 03/04/2015
            if ($hrefVolInfo->{$strVol}->{'state'} ne 'offline')  {

            # Test if various thresholds are defined and if they are then test if the monitored object exceeds them.
            if (defined($hrefThresholds->{'space-percent'}) || defined($hrefThresholds->{'space-count'})) {
                    # Prepare certain variables pre-check to reduce code duplication.
```

....

It seems better with that test (perhaps not 'elegant' in perl, but I 'm not perl developper)

**Comment by ditol** [comment]
Same issue on restricted volumes

**Comment by willemdh** [comment]
Added your piece of code to the dev branch.

**Comment by willemdh** [comment]
@Copis Feel free to submit a pr to the deb branch.

**Comment by willemdh** [comment]
Please submit a pr to the dev branch, as it is ahead several pr's.

**Comment by Copis** [comment]
Sorry I moved this PR to dev branch
