### ISSUE TITLE
Sanpmirror lag time

### ISSUE THREAD

**Issue by alokispandey** [willemdh/check_netapp_ontap#36]
How to monitor snapmirror lag time, 

/usr/local/nagios/libexec/check_netapp_ontap.pl -H NETAPP_C-MODE_IP   -n SVM_NODE -u USERNAME -p PASSWD  -c public -o snapmirror_health -w 1h -c 2h
OK - No problems found (0 checked)

Above return 0 checked?

**Comment by alokispandey** [comment]
Please suggest..?

**Comment by alokispandey** [comment]
no one ?

**Comment by willemdh** [comment]
@alokispandey TOo little info.. Closing this, please recreate if you still have issues..
