### ISSUE TITLE
Can't locate UserAgent.pm. Compilation Failed

### ISSUE THREAD

**Issue by khairulzuan** [willemdh/check_netapp_ontap#37]
I installed Nagios 4.2.1 on CentOS Linux release 7.2.1511 (Core). Everything worked perfect. I want to monitor my NetApp Release 8.1.3.7-Mode.

I use tutorial How To from http://outsideit.net/check-netapp-ontap/

given chown nagios:nagios /usr/local/nagios/libexec/check_netapp_ontap.pl
given chmod 644 /usr/local/nagios/libexec/check_netapp_ontap.pl

copy Netapp/\* to  /usr/lib64/perl5

but when i try to run test command

./check_netapp_ontap.pl the error below appear. is it because Netapp SDK? How can I solve this error?

\Can't locate LWP/UserAgent.pm in @INC (@INC contains: /usr/local/lib64/perl5 /u
BEGIN failed--compilation aborted at /usr/lib64/perl5/NaServer.pm line 27.
Compilation failed in require at ./check_netapp_ontap.pl line 26.
BEGIN failed--compilation aborted at ./check_netapp_ontap.pl line 26.

**Comment by khairulzuan** [comment]
I already solved this problem. The issue is i not install the depencies perl LWP:UserAgent. 

yum install perl-LWP-Protocol-https.noarch

**Comment by willemdh** [comment]
@khairulzuan Please close your issues if it's no longer an issue..
