### ISSUE TITLE
Failed filer health query: The request was for an API version which is not supported by the appliance

### ISSUE THREAD

**Issue by jvrrn** [willemdh/check_netapp_ontap#38]
Hello,

Just updated ontap & the filer health query:
 netapp_alarms
is returning an error about the API version

Wll this require an update to the script?

**Comment by willemdh** [comment]
What version of NetApp Ontap cluster are you on?

**Comment by ftpproxy** [comment]
I would say he is using NetApp Release 9, because "dashboard" is deprecated in this release.

**Comment by willemdh** [comment]
Ok, well I'm still on 8.2, so no idea about what changed in 9..

**Comment by jvrrn** [comment]
yep it is 9.
Will have to find a similar call...

**Comment by willemdh** [comment]
@jvrrn Did you ever found out how to fix it on NetApp 9?

**Comment by vanboxen** [comment]
I'm getting the same error message only for the netapp_alarms (using NetApp Ontap version 9.1P3) the others alerts are all good. Any ideas?

**Comment by jvrrn** [comment]
From what I recall, this is due to a call being deprecated & now completely dropped

Unfortunately this will no longer work


Kind Regards

Javier Ron
Servers & Storage, Team
Queen Mary University of London, TB202
Mile End Road
London E1 4NS
Mob: +44 (0) 777 613 8899
Email: j.ron@qmul.ac.uk
________________________________

**Comment by Elvon** [comment]
Hey,
i'm also getting the error 

> Failed filer health query: The request was for an API version which is not supported by the appliance

I'm on OnTab 9.1

Is there any chance that we get a updated version of this plugin? :-)

Thanks,
Marcel

**Comment by tgoetheyn** [comment]
the "netapp_alarms" is indeed depricated in Ontap 9
If you check the command manual you'll see that the "dashboard alarm" commands don't excist in Ontap9
