### ISSUE TITLE
disk_health ontap 9.1 FAS 2650

### ISSUE THREAD

**Issue by mikep12** [willemdh/check_netapp_ontap#40]
Hi, we're using your plugin to monitor a fresh FAS 2650. w/ Ontap 9.1
Works fine but some disks monitored with disk_health always show "yellow" due to scrubbing. This seems to be normal according to NetApp:
[https://library.netapp.com/ecmdocs/ECMP1196912/html/GUID-0C6E982A-AC7C-44BA-93BF-4DEA7EE15576.html](https://library.netapp.com/ecmdocs/ECMP1196912/html/GUID-0C6E982A-AC7C-44BA-93BF-4DEA7EE15576.html)
Any help?

**Comment by Copis** [comment]
You could modify this script at line 115 and change the return state for scrubbing like this:
`$intState = get_nagios_state($intState, 0);`

**Comment by willemdh** [comment]
Closing this, let me know if not solved, then I'll reopen.
