### ISSUE TITLE
volume_health and offline volume

### ISSUE THREAD

**Issue by ChristopheMasson** [willemdh/check_netapp_ontap#46]
Hi,

When a volume is offline, volume_health use the uninitialized value in $hrefVolInfo->{$strVol}->{'space-total'} (line 1202 version 2.5.10) because offline volume does'nt have space information.

You need to test if $hrefVolInfo->{$strVol}->{'space-total' id defined or not before does the division.

Test:
I have add some print
====
		#	if (defined($hrefVolInfo->{$strVol}->{'space-total'})) {
			    print ($hrefThresholds->{'space-percent'} . "\n");
			    print ($strVol . "\n");
			    print ($hrefVolInfo->{$strVol}->{'space-total'} . "\n");
				my $intUsedPercent = ($hrefVolInfo->{$strVol}->{'space-used'} / $hrefVolInfo->{$strVol}->{'space-total'}) * 100;
            	$intUsedPercent = floor($intUsedPercent + 0.5);
            	my $strReadableUsed = space_to_human_readable($hrefVolInfo->{$strVol}->{'space-used'});
            	my $strReadableTotal = space_to_human_readable($hrefVolInfo->{$strVol}->{'space-total'});
            	my $strNewMessage = $strVol . " - " . $strReadableUsed . "/" . $strReadableTotal . " (" . $intUsedPercent . "%) SPACE USED";
=====

perl check_netapp_ontap-debug.pl -o volume_health -H keris.enssat.fr -u xxxx -p xxxx -w offline -n sftestkerb
sftestkerb/vol_04052017_174853 is offline

perl check_netapp_ontap-debug.pl -o volume_health -H keris.enssat.fr -u xxxx -p xxxx -w 50% -c 51% -n sftestkerb
51
sftestkerb/sfTestKerbData
2638827909120
51
sftestkerb/vol_04052017_174853
Use of uninitialized value in concatenation (.) or string at check_netapp_ontap-debug.pl line 1204.

Use of uninitialized value in division (/) at check_netapp_ontap-debug.pl line 1205.
Use of uninitialized value in division (/) at check_netapp_ontap-debug.pl line 1205.
Illegal division by zero at check_netapp_ontap-debug.pl line 1205.

**Comment by Copis** [comment]
This issue was comented at  #3

**Comment by ChristopheMasson** [comment]
Oups sorry i didn't see
