### ISSUE TITLE
Ontap 9.1 - is scrubbing

### ISSUE THREAD

**Issue by loderlu** [willemdh/check_netapp_ontap#50]
Since we updated our Netapp to the Ontap Version 9.1 (before 8.3) we get warnings from the disk_health check. Some disks are in the status "is scrubbing". Is this a known issue? How can we resolve it?
![nagstamon 1 0rc2_2017-07-06_15-31-38](https://user-images.githubusercontent.com/25492075/27913406-45a33d2e-6260-11e7-84c9-79a4a25c09fb.png)

thanks

**Comment by willemdh** [comment]
@loderlu Difficult to say as we are still on 8.2

**Comment by Copis** [comment]
Hi @loderlu please review this [PR44](https://github.com/willemdh/check_netapp_ontap/pull/44)

**Comment by willemdh** [comment]
@loderlu Closing this, let us know if you are still experiencing issues.
