### ISSUE TITLE
volume_health, Division by zero when offline volumes exist

### ISSUE THREAD

**Issue by scootersmk** [willemdh/check_netapp_ontap#51]
Running latest version(2.5.10) of this script, also occurred in previous versions at different line numbers.

Ontapp version 9.2, with offline volumes present:
```
# ./check_netapp_ontap.pl -H hostname -u user -p password --option volume_health -w 98%,96%i -c 99%,98%i
Use of uninitialized value in division (/) at ./check_netapp_ontap.pl line 1207.
Use of uninitialized value in division (/) at ./check_netapp_ontap.pl line 1207.
Illegal division by zero at ./check_netapp_ontap.pl line 1207.
```

It looks like this script needs more logic to ignore  offline volumes because this command works(adding offline as a critical state):
```
# ./check_netapp_ontap.pl -H hostname -u user -p password --option volume_health -w 98%,96%i -c 99%,98%i,offline
svm1/home1 - 100950109/105382963 (96%) INODES USED, svm2/home1_snap - 100869566/105382963 (96%) INODES USED 
```

Script also works as expected if you bring all volumes back online.

**Comment by Copis** [comment]
Is the same to Issue #3

**Comment by willemdh** [comment]
@scootersmk Closing this, let us know if you are still experiencing issues using latest release
