### ISSUE TITLE
ontap 8.3 : advanced partitionning (adp) ,false CRITICAL RESULT

### ISSUE THREAD

**Issue by aderumier** [willemdh/check_netapp_ontap#6]
Hi, with ontap 8.3 with new adp feature
http://www.datacenterdan.com/blog/netapp-dataontap-83-adp-root-disk-slice-deep-dive

disk and nodes check, give us:

$USER1$/check_nac.py -H $HOSTADDRESS$ -u $ARG1$ -p $ARG2$ -t disks

NAC CRITICAL - disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared disk None is shared

$USER1$/check_nac.py -H $HOSTADDRESS$ -u $ARG1$ -p $ARG2$ -t nodes

NAC CRITICAL - node node1 has critical alarm for aggregate_used aggr0_cluster_01_0 node node2 has critical alarm for aggregate_used aggr0_cluster_02_0

**Comment by willemdh** [comment]
Hey Aderumier,

Unfortunately we are still on 8.2, so I'm unable to test anything related to 8.3. It could take months before we decide to upgrade.

Did you write a wrapper script in Python? check_nac.py?

Grtz

**Comment by aderumier** [comment]
Oh, sorry, I really don't known what I have done, but It was not with your plugin. (I was pretty sure to use it).
It's working perfectly with ontap 8.3. (I just have migrated all my monitoring to your plugin).

Sorry for the noise.
