### ISSUE TITLE
Failed test query: NaServer::parse_xml

### ISSUE THREAD

**Issue by sabyvan** [willemdh/check_netapp_ontap#72]
**Issue Detail**

* check_netapp_ontap version: 3.01.171611
* NetApp Ontap version: 9.3
* Monitoring solution: EyesOfNetwork 4.1 / Centos6.5

Hello,

I try to use the script but when i run the following command :
check_netapp_ontap.pl -H HOST_IP -u admin -p admin_pass -o cluster_health 
(for exemple, same issue all the time)

I have this error:

 ```
Failed test query: NaServer::parse_xml - Error in parsing xml:
syntax error at line 1, column 49, byte 49:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
================================================^
<html><head>
<title>400 Bad Request</title>
 at /usr/lib64/perl5/XML/Parser.pm line 187
I
```

 I don't really understand what is the problem here...

maybe my perl version is too older (perl-5.10.1-136.el6.x86_64) or something like that
I searched requirements  but i didn't found anything (https://outsideit.net/check-netapp-ontap/ is offline)

thanks for your help

**Comment by tgoetheyn** [comment]
This script requires NetApp Manageability SDK for Perl to be installed. Can be found on https://mysupport.netapp.com/NOW/cgi-bin/software

**Comment by sabyvan** [comment]
Thank you !
problem solved with the last SDK, everthings works fine now!
