### ISSUE TITLE
400 Bad Request with ONTAP 9.3

### ISSUE THREAD

**Issue by ch0use** [willemdh/check_netapp_ontap#76]
**Issue Type**

Bug report 

**Issue Detail**

* check_netapp_ontap version: v3.01.171611
* NetApp Ontap version: 9.3
* Monitoring solution: Opsview/Nagios

**Expected Behavior**
return aggregate usage

**Actual Behavior**
./check_netapp_ontap.pl -H <netapp> -u opsview -p <pass> -o aggregate_health -m include,n1_aggr0 -w 95% -c 98%
Smartmatch is experimental at ./check_netapp_ontap.pl line 425.
Smartmatch is experimental at ./check_netapp_ontap.pl line 426.
Smartmatch is experimental at ./check_netapp_ontap.pl line 427.
Failed test query: NaServer::parse_xml - Error in parsing xml:
syntax error at line 1, column 49, byte 49:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
================================================^
<html><head>
<title>400 Bad Request</title>
 at /usr/local/nagios/perl/lib/x86_64-linux-gnu-thread-multi/XML/Parser.pm line 187.

**How to reproduce Behavior**
Run it any time, nothing seems to work. Have configured opsview user with ontapi application readonly role and a password.

**Comment by Copis** [comment]
Hi @ch0use are you using last NetApp SDK available? If you aren't using last 9.3 Perl modules you are unable to monitor new ONTAP systems.

**Comment by bert-jan** [comment]
Had the same issue, after installing the latest available 9.3 NetApp SDK everything worked fine again.

**Comment by ch0use** [comment]
yep, that did the trick, thanks. knew it was something dumb but was thrown off by the xml/parser.pm stuff.
