### ISSUE TITLE
Use of uninitialized value $intState in exit at ./check_netapp_ontap.pl line 2137

### ISSUE THREAD

**Issue by sushant14bhadauria** [willemdh/check_netapp_ontap#80]
In Last line of code . while exiting getting error $intState uninitialized 

# Print the output and exit with the resulting state.
$strOutput .= "\n";
print $strOutput;
exit $intState;

I am using these option in the plugin
=============================================================
./check_netapp_ontap.pl -H X.X.X.X -node xyz.zyz.com -user xxx -password xxx –option volume_health

**Comment by willemdh** [comment]
@sushant14bhadauria This issue has way too little info, please recreate if you are still experiencing issues with more info..
